version: "2.3"
services:
  process: &default
    image: esrgan
    volumes:
      - '.:/app/esrgan'
    working_dir: /app/esrgan
    entrypoint: python3 -u process.py
  process-gpu:
    <<: *default
    runtime: nvidia
    entrypoint: python3 -u process.py --gpu
  net_interp:
    <<: *default
    entrypoint: python3 -u net_interp.py
